spring:
  application:
    name: chat-app
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
  #    show-sql: true
  main:
    banner-mode: off
#logging:
#  level:
#    root: ERROR